apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: cluster-admin-binding
spec:
  validationActions:
    - Audit
  matchConstraints:
    resourceRules:
      - apiGroups: ["rbac.authorization.k8s.io"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["clusterrolebindings", "rolebindings"]
  validations:
    - expression: >-
        object.roleRef.name != 'cluster-admin'
      message: >-
        Binding the built-in cluster-admin role is not allowed.
