apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: host-namespaces
spec:
  validationActions:
    - Audit
  autogen:
    podControllers:
      controllers:
        - deployments
        - statefulsets
        - daemonsets
        - replicasets
        - jobs
        - cronjobs
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >-
        !object.spec.?hostNetwork.orValue(false) &&
        !object.spec.?hostPID.orValue(false) &&
        !object.spec.?hostIPC.orValue(false)
      message: >-
        Sharing the host network, PID or IPC namespace is not allowed.
