// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: admission_event.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AdmissionEvent is a normalized result of a single Kyverno policy evaluation.
// It is produced by admission-monitor and published to history-api the same way
// event-processor publishes runtime_event.RuntimeEvent.
type AdmissionEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id (as UUID) is generated by admission-monitor, so that it can be used in notifier templates
	// when sending notifications, for building URL pointing to a particular event, or as a supplementary info
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	KyvernoVersion string                 `protobuf:"bytes,2,opt,name=kyverno_version,json=kyvernoVersion,proto3" json:"kyverno_version,omitempty"`
	RegisteredAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	Resource       *Resource              `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Threats        []*Threat              `protobuf:"bytes,5,rep,name=threats,proto3" json:"threats,omitempty"`
	// blocked is true when Kyverno itself denied the request (policy action is ENFORCE).
	Blocked          bool     `protobuf:"varint,6,opt,name=blocked,proto3" json:"blocked,omitempty"`
	IsIncident       bool     `protobuf:"varint,7,opt,name=is_incident,json=isIncident,proto3" json:"is_incident,omitempty"`
	IncidentSeverity string   `protobuf:"bytes,8,opt,name=incident_severity,json=incidentSeverity,proto3" json:"incident_severity,omitempty"`
	BlockBy          []string `protobuf:"bytes,9,rep,name=block_by,json=blockBy,proto3" json:"block_by,omitempty"`
	NotifyBy         []string `protobuf:"bytes,10,rep,name=notify_by,json=notifyBy,proto3" json:"notify_by,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AdmissionEvent) Reset() {
	*x = AdmissionEvent{}
	mi := &file_admission_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmissionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmissionEvent) ProtoMessage() {}

func (x *AdmissionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_admission_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmissionEvent.ProtoReflect.Descriptor instead.
func (*AdmissionEvent) Descriptor() ([]byte, []int) {
	return file_admission_event_proto_rawDescGZIP(), []int{0}
}

func (x *AdmissionEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdmissionEvent) GetKyvernoVersion() string {
	if x != nil {
		return x.KyvernoVersion
	}
	return ""
}

func (x *AdmissionEvent) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *AdmissionEvent) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *AdmissionEvent) GetThreats() []*Threat {
	if x != nil {
		return x.Threats
	}
	return nil
}

func (x *AdmissionEvent) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *AdmissionEvent) GetIsIncident() bool {
	if x != nil {
		return x.IsIncident
	}
	return false
}

func (x *AdmissionEvent) GetIncidentSeverity() string {
	if x != nil {
		return x.IncidentSeverity
	}
	return ""
}

func (x *AdmissionEvent) GetBlockBy() []string {
	if x != nil {
		return x.BlockBy
	}
	return nil
}

func (x *AdmissionEvent) GetNotifyBy() []string {
	if x != nil {
		return x.NotifyBy
	}
	return nil
}

// Resource describes the object the policy was evaluated against.
type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Uid           string                 `protobuf:"bytes,5,opt,name=uid,proto3" json:"uid,omitempty"`
	NodeName      string                 `protobuf:"bytes,6,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Containers    []*Container           `protobuf:"bytes,7,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_admission_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_admission_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_admission_event_proto_rawDescGZIP(), []int{1}
}

func (x *Resource) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Resource) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Resource) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Resource) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Resource) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImageName     string                 `protobuf:"bytes,2,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	Registry      string                 `protobuf:"bytes,3,opt,name=registry,proto3" json:"registry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_admission_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_admission_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_admission_event_proto_rawDescGZIP(), []int{2}
}

func (x *Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Container) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *Container) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

// Threat is a single failed policy rule. Kyverno policy plays the same role here
// as a WASM detector does in event-processor.
type Threat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *Policy                `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Threat) Reset() {
	*x = Threat{}
	mi := &file_admission_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Threat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Threat) ProtoMessage() {}

func (x *Threat) ProtoReflect() protoreflect.Message {
	mi := &file_admission_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Threat.ProtoReflect.Descriptor instead.
func (*Threat) Descriptor() ([]byte, []int) {
	return file_admission_event_proto_rawDescGZIP(), []int{3}
}

func (x *Threat) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *Threat) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

// Policy identifies the Kyverno policy and rule which produced the threat.
type Policy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is "<policy name>/<rule name>", it is stable and is used to whitelist a threat in policy-enforcer rules.
	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rule        string `protobuf:"bytes,3,opt,name=rule,proto3" json:"rule,omitempty"`
	Category    string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// source is reported by Kyverno, e.g. "KyvernoValidatingPolicy" or "KyvernoImageValidatingPolicy".
	Source        string               `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Action        KyvernoPolicy_Action `protobuf:"varint,7,opt,name=action,proto3,enum=admission_config.KyvernoPolicy_Action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_admission_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_admission_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_admission_event_proto_rawDescGZIP(), []int{4}
}

func (x *Policy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Policy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Policy) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *Policy) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Policy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Policy) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Policy) GetAction() KyvernoPolicy_Action {
	if x != nil {
		return x.Action
	}
	return KyvernoPolicy_AUDIT
}

var File_admission_event_proto protoreflect.FileDescriptor

const file_admission_event_proto_rawDesc = "" +
	"\n" +
	"\x15admission_event.proto\x12\x0fadmission_event\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16admission_config.proto\"\x94\x03\n" +
	"\x0eAdmissionEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fkyverno_version\x18\x02 \x01(\tR\x0ekyvernoVersion\x12?\n" +
	"\rregistered_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x125\n" +
	"\bresource\x18\x04 \x01(\v2\x19.admission_event.ResourceR\bresource\x121\n" +
	"\athreats\x18\x05 \x03(\v2\x17.admission_event.ThreatR\athreats\x12\x18\n" +
	"\ablocked\x18\x06 \x01(\bR\ablocked\x12\x1f\n" +
	"\vis_incident\x18\a \x01(\bR\n" +
	"isIncident\x12+\n" +
	"\x11incident_severity\x18\b \x01(\tR\x10incidentSeverity\x12\x19\n" +
	"\bblock_by\x18\t \x03(\tR\ablockBy\x12\x1b\n" +
	"\tnotify_by\x18\n" +
	" \x03(\tR\bnotifyBy\"\xdc\x01\n" +
	"\bResource\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\tR\x03uid\x12\x1b\n" +
	"\tnode_name\x18\x06 \x01(\tR\bnodeName\x12:\n" +
	"\n" +
	"containers\x18\a \x03(\v2\x1a.admission_event.ContainerR\n" +
	"containers\"Z\n" +
	"\tContainer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"image_name\x18\x02 \x01(\tR\timageName\x12\x1a\n" +
	"\bregistry\x18\x03 \x01(\tR\bregistry\"U\n" +
	"\x06Threat\x12/\n" +
	"\x06policy\x18\x01 \x01(\v2\x17.admission_event.PolicyR\x06policy\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\"\xd6\x01\n" +
	"\x06Policy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04rule\x18\x03 \x01(\tR\x04rule\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12>\n" +
	"\x06action\x18\a \x01(\x0e2&.admission_config.KyvernoPolicy.ActionR\x06actionB\aZ\x05./apib\x06proto3"

var (
	file_admission_event_proto_rawDescOnce sync.Once
	file_admission_event_proto_rawDescData []byte
)

func file_admission_event_proto_rawDescGZIP() []byte {
	file_admission_event_proto_rawDescOnce.Do(func() {
		file_admission_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admission_event_proto_rawDesc), len(file_admission_event_proto_rawDesc)))
	})
	return file_admission_event_proto_rawDescData
}

var file_admission_event_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_admission_event_proto_goTypes = []any{
	(*AdmissionEvent)(nil),        // 0: admission_event.AdmissionEvent
	(*Resource)(nil),              // 1: admission_event.Resource
	(*Container)(nil),             // 2: admission_event.Container
	(*Threat)(nil),                // 3: admission_event.Threat
	(*Policy)(nil),                // 4: admission_event.Policy
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(KyvernoPolicy_Action)(0),     // 6: admission_config.KyvernoPolicy.Action
}
var file_admission_event_proto_depIdxs = []int32{
	5, // 0: admission_event.AdmissionEvent.registered_at:type_name -> google.protobuf.Timestamp
	1, // 1: admission_event.AdmissionEvent.resource:type_name -> admission_event.Resource
	3, // 2: admission_event.AdmissionEvent.threats:type_name -> admission_event.Threat
	2, // 3: admission_event.Resource.containers:type_name -> admission_event.Container
	4, // 4: admission_event.Threat.policy:type_name -> admission_event.Policy
	6, // 5: admission_event.Policy.action:type_name -> admission_config.KyvernoPolicy.Action
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_admission_event_proto_init() }
func file_admission_event_proto_init() {
	if File_admission_event_proto != nil {
		return
	}
	file_admission_config_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admission_event_proto_rawDesc), len(file_admission_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_admission_event_proto_goTypes,
		DependencyIndexes: file_admission_event_proto_depIdxs,
		MessageInfos:      file_admission_event_proto_msgTypes,
	}.Build()
	File_admission_event_proto = out.File
	file_admission_event_proto_goTypes = nil
	file_admission_event_proto_depIdxs = nil
}
