// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: admission_history.proto

package api

import (
	context "context"
	api "github.com/runtime-radar/runtime-radar/admission-monitor/api"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdmissionHistory_Read_FullMethodName                      = "/admission_history.AdmissionHistory/Read"
	AdmissionHistory_ListAdmissionEventSlice_FullMethodName   = "/admission_history.AdmissionHistory/ListAdmissionEventSlice"
	AdmissionHistory_FilterAdmissionEventSlice_FullMethodName = "/admission_history.AdmissionHistory/FilterAdmissionEventSlice"
)

// AdmissionHistoryClient is the client API for AdmissionHistory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdmissionHistoryClient interface {
	Read(ctx context.Context, in *ReadAdmissionEventReq, opts ...grpc.CallOption) (*api.AdmissionEvent, error)
	ListAdmissionEventSlice(ctx context.Context, in *ListAdmissionEventSliceReq, opts ...grpc.CallOption) (*ListAdmissionEventSliceResp, error)
	FilterAdmissionEventSlice(ctx context.Context, in *FilterAdmissionEventSliceReq, opts ...grpc.CallOption) (*ListAdmissionEventSliceResp, error)
}

type admissionHistoryClient struct {
	cc grpc.ClientConnInterface
}

func NewAdmissionHistoryClient(cc grpc.ClientConnInterface) AdmissionHistoryClient {
	return &admissionHistoryClient{cc}
}

func (c *admissionHistoryClient) Read(ctx context.Context, in *ReadAdmissionEventReq, opts ...grpc.CallOption) (*api.AdmissionEvent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(api.AdmissionEvent)
	err := c.cc.Invoke(ctx, AdmissionHistory_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *admissionHistoryClient) ListAdmissionEventSlice(ctx context.Context, in *ListAdmissionEventSliceReq, opts ...grpc.CallOption) (*ListAdmissionEventSliceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdmissionEventSliceResp)
	err := c.cc.Invoke(ctx, AdmissionHistory_ListAdmissionEventSlice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *admissionHistoryClient) FilterAdmissionEventSlice(ctx context.Context, in *FilterAdmissionEventSliceReq, opts ...grpc.CallOption) (*ListAdmissionEventSliceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdmissionEventSliceResp)
	err := c.cc.Invoke(ctx, AdmissionHistory_FilterAdmissionEventSlice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdmissionHistoryServer is the server API for AdmissionHistory service.
// All implementations must embed UnimplementedAdmissionHistoryServer
// for forward compatibility.
type AdmissionHistoryServer interface {
	Read(context.Context, *ReadAdmissionEventReq) (*api.AdmissionEvent, error)
	ListAdmissionEventSlice(context.Context, *ListAdmissionEventSliceReq) (*ListAdmissionEventSliceResp, error)
	FilterAdmissionEventSlice(context.Context, *FilterAdmissionEventSliceReq) (*ListAdmissionEventSliceResp, error)
	mustEmbedUnimplementedAdmissionHistoryServer()
}

// UnimplementedAdmissionHistoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdmissionHistoryServer struct{}

func (UnimplementedAdmissionHistoryServer) Read(context.Context, *ReadAdmissionEventReq) (*api.AdmissionEvent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedAdmissionHistoryServer) ListAdmissionEventSlice(context.Context, *ListAdmissionEventSliceReq) (*ListAdmissionEventSliceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAdmissionEventSlice not implemented")
}
func (UnimplementedAdmissionHistoryServer) FilterAdmissionEventSlice(context.Context, *FilterAdmissionEventSliceReq) (*ListAdmissionEventSliceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FilterAdmissionEventSlice not implemented")
}
func (UnimplementedAdmissionHistoryServer) mustEmbedUnimplementedAdmissionHistoryServer() {}
func (UnimplementedAdmissionHistoryServer) testEmbeddedByValue()                          {}

// UnsafeAdmissionHistoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdmissionHistoryServer will
// result in compilation errors.
type UnsafeAdmissionHistoryServer interface {
	mustEmbedUnimplementedAdmissionHistoryServer()
}

func RegisterAdmissionHistoryServer(s grpc.ServiceRegistrar, srv AdmissionHistoryServer) {
	// If the following call pancis, it indicates UnimplementedAdmissionHistoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdmissionHistory_ServiceDesc, srv)
}

func _AdmissionHistory_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAdmissionEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdmissionHistoryServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdmissionHistory_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdmissionHistoryServer).Read(ctx, req.(*ReadAdmissionEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdmissionHistory_ListAdmissionEventSlice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdmissionEventSliceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdmissionHistoryServer).ListAdmissionEventSlice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdmissionHistory_ListAdmissionEventSlice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdmissionHistoryServer).ListAdmissionEventSlice(ctx, req.(*ListAdmissionEventSliceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdmissionHistory_FilterAdmissionEventSlice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterAdmissionEventSliceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdmissionHistoryServer).FilterAdmissionEventSlice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdmissionHistory_FilterAdmissionEventSlice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdmissionHistoryServer).FilterAdmissionEventSlice(ctx, req.(*FilterAdmissionEventSliceReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AdmissionHistory_ServiceDesc is the grpc.ServiceDesc for AdmissionHistory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdmissionHistory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admission_history.AdmissionHistory",
	HandlerType: (*AdmissionHistoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _AdmissionHistory_Read_Handler,
		},
		{
			MethodName: "ListAdmissionEventSlice",
			Handler:    _AdmissionHistory_ListAdmissionEventSlice_Handler,
		},
		{
			MethodName: "FilterAdmissionEventSlice",
			Handler:    _AdmissionHistory_FilterAdmissionEventSlice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admission_history.proto",
}
