{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.serviceAccountName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
{{- $names := list -}}
{{- range (default (list) .Values.global.imagePullSecrets) -}}
{{- $names = append $names (kindIs "map" . | ternary .name .) -}}
{{- end -}}
{{- if and $names (has $.Values.imagePullSecret.name $names | ternary $.Values.imagePullSecret.password true) }}
{{ include "common.imagePullSecrets" . }}
{{- end }}
{{- end }}
