// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: assistant.proto

package api

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the AI integration whose model answers.
	IntegrationId string `protobuf:"bytes,1,opt,name=integration_id,json=integrationId,proto3" json:"integration_id,omitempty"`
	// The conversation so far, oldest first, ending with the user's new message.
	// No conversation state is kept on the server: the client sends the whole
	// history it wants the model to see.
	Conversation []*ChatMessage `protobuf:"bytes,2,rep,name=conversation,proto3" json:"conversation,omitempty"`
	// Optional identifier of a runtime event the question is about. The event
	// itself is never taken from the client: the assistant reads it through the
	// tools, so that what the model sees is what the system recorded.
	EventId       *string `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3,oneof" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatReq) Reset() {
	*x = ChatReq{}
	mi := &file_assistant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReq) ProtoMessage() {}

func (x *ChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReq.ProtoReflect.Descriptor instead.
func (*ChatReq) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{0}
}

func (x *ChatReq) GetIntegrationId() string {
	if x != nil {
		return x.IntegrationId
	}
	return ""
}

func (x *ChatReq) GetConversation() []*ChatMessage {
	if x != nil {
		return x.Conversation
	}
	return nil
}

func (x *ChatReq) GetEventId() string {
	if x != nil && x.EventId != nil {
		return *x.EventId
	}
	return ""
}

type ChatMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Role of the author: "user" or "assistant". Any other value is rejected;
	// tool traffic belongs to the server side of the loop and is not replayed
	// by clients.
	Role          string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_assistant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ChatChunk is one piece of the answer. Exactly one field is set.
type ChatChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Chunk:
	//
	//	*ChatChunk_Delta
	//	*ChatChunk_ToolActivity
	//	*ChatChunk_Done
	Chunk         isChatChunk_Chunk `protobuf_oneof:"chunk"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatChunk) Reset() {
	*x = ChatChunk{}
	mi := &file_assistant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatChunk) ProtoMessage() {}

func (x *ChatChunk) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatChunk.ProtoReflect.Descriptor instead.
func (*ChatChunk) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{2}
}

func (x *ChatChunk) GetChunk() isChatChunk_Chunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ChatChunk) GetDelta() string {
	if x != nil {
		if x, ok := x.Chunk.(*ChatChunk_Delta); ok {
			return x.Delta
		}
	}
	return ""
}

func (x *ChatChunk) GetToolActivity() *ToolActivity {
	if x != nil {
		if x, ok := x.Chunk.(*ChatChunk_ToolActivity); ok {
			return x.ToolActivity
		}
	}
	return nil
}

func (x *ChatChunk) GetDone() *Done {
	if x != nil {
		if x, ok := x.Chunk.(*ChatChunk_Done); ok {
			return x.Done
		}
	}
	return nil
}

type isChatChunk_Chunk interface {
	isChatChunk_Chunk()
}

type ChatChunk_Delta struct {
	// delta is a piece of the answer's text, to be appended as it arrives.
	Delta string `protobuf:"bytes,1,opt,name=delta,proto3,oneof"`
}

type ChatChunk_ToolActivity struct {
	// tool_activity reports that the assistant started or finished a tool.
	ToolActivity *ToolActivity `protobuf:"bytes,2,opt,name=tool_activity,json=toolActivity,proto3,oneof"`
}

type ChatChunk_Done struct {
	// done ends the answer.
	Done *Done `protobuf:"bytes,3,opt,name=done,proto3,oneof"`
}

func (*ChatChunk_Delta) isChatChunk_Chunk() {}

func (*ChatChunk_ToolActivity) isChatChunk_Chunk() {}

func (*ChatChunk_Done) isChatChunk_Chunk() {}

type ToolActivity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the tool, for example search_docs.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Phase is "started" or "finished".
	Phase string `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	// error is set on a finished phase when the tool failed. The assistant
	// carries on: a failed tool is an answer the model has to account for.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolActivity) Reset() {
	*x = ToolActivity{}
	mi := &file_assistant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolActivity) ProtoMessage() {}

func (x *ToolActivity) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolActivity.ProtoReflect.Descriptor instead.
func (*ToolActivity) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{3}
}

func (x *ToolActivity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolActivity) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ToolActivity) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Done struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stop_reason is "end_turn" when the assistant finished on its own,
	// "max_iterations" when the agent loop ran out of steps, or "error".
	StopReason string `protobuf:"bytes,1,opt,name=stop_reason,json=stopReason,proto3" json:"stop_reason,omitempty"`
	// error is set when stop_reason is "error".
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// iterations is how many model turns the answer took.
	Iterations    uint32 `protobuf:"varint,3,opt,name=iterations,proto3" json:"iterations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Done) Reset() {
	*x = Done{}
	mi := &file_assistant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Done) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Done) ProtoMessage() {}

func (x *Done) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Done.ProtoReflect.Descriptor instead.
func (*Done) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{4}
}

func (x *Done) GetStopReason() string {
	if x != nil {
		return x.StopReason
	}
	return ""
}

func (x *Done) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Done) GetIterations() uint32 {
	if x != nil {
		return x.Iterations
	}
	return 0
}

var File_assistant_proto protoreflect.FileDescriptor

const file_assistant_proto_rawDesc = "" +
	"\n" +
	"\x0fassistant.proto\x12\tassistant\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x99\x01\n" +
	"\aChatReq\x12%\n" +
	"\x0eintegration_id\x18\x01 \x01(\tR\rintegrationId\x12:\n" +
	"\fconversation\x18\x02 \x03(\v2\x16.assistant.ChatMessageR\fconversation\x12\x1e\n" +
	"\bevent_id\x18\x03 \x01(\tH\x00R\aeventId\x88\x01\x01B\v\n" +
	"\t_event_id\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x93\x01\n" +
	"\tChatChunk\x12\x16\n" +
	"\x05delta\x18\x01 \x01(\tH\x00R\x05delta\x12>\n" +
	"\rtool_activity\x18\x02 \x01(\v2\x17.assistant.ToolActivityH\x00R\ftoolActivity\x12%\n" +
	"\x04done\x18\x03 \x01(\v2\x0f.assistant.DoneH\x00R\x04doneB\a\n" +
	"\x05chunk\"N\n" +
	"\fToolActivity\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"]\n" +
	"\x04Done\x12\x1f\n" +
	"\vstop_reason\x18\x01 \x01(\tR\n" +
	"stopReason\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1e\n" +
	"\n" +
	"iterations\x18\x03 \x01(\rR\n" +
	"iterations2l\n" +
	"\x13AssistantController\x12U\n" +
	"\x04Chat\x12\x12.assistant.ChatReq\x1a\x14.assistant.ChatChunk\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/assistant/chat0\x01B\x1b\x92A\x11\x12\x0f\n" +
	"\rAssistant APIZ\x05./apib\x06proto3"

var (
	file_assistant_proto_rawDescOnce sync.Once
	file_assistant_proto_rawDescData []byte
)

func file_assistant_proto_rawDescGZIP() []byte {
	file_assistant_proto_rawDescOnce.Do(func() {
		file_assistant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assistant_proto_rawDesc), len(file_assistant_proto_rawDesc)))
	})
	return file_assistant_proto_rawDescData
}

var file_assistant_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_assistant_proto_goTypes = []any{
	(*ChatReq)(nil),      // 0: assistant.ChatReq
	(*ChatMessage)(nil),  // 1: assistant.ChatMessage
	(*ChatChunk)(nil),    // 2: assistant.ChatChunk
	(*ToolActivity)(nil), // 3: assistant.ToolActivity
	(*Done)(nil),         // 4: assistant.Done
}
var file_assistant_proto_depIdxs = []int32{
	1, // 0: assistant.ChatReq.conversation:type_name -> assistant.ChatMessage
	3, // 1: assistant.ChatChunk.tool_activity:type_name -> assistant.ToolActivity
	4, // 2: assistant.ChatChunk.done:type_name -> assistant.Done
	0, // 3: assistant.AssistantController.Chat:input_type -> assistant.ChatReq
	2, // 4: assistant.AssistantController.Chat:output_type -> assistant.ChatChunk
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_assistant_proto_init() }
func file_assistant_proto_init() {
	if File_assistant_proto != nil {
		return
	}
	file_assistant_proto_msgTypes[0].OneofWrappers = []any{}
	file_assistant_proto_msgTypes[2].OneofWrappers = []any{
		(*ChatChunk_Delta)(nil),
		(*ChatChunk_ToolActivity)(nil),
		(*ChatChunk_Done)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assistant_proto_rawDesc), len(file_assistant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assistant_proto_goTypes,
		DependencyIndexes: file_assistant_proto_depIdxs,
		MessageInfos:      file_assistant_proto_msgTypes,
	}.Build()
	File_assistant_proto = out.File
	file_assistant_proto_goTypes = nil
	file_assistant_proto_depIdxs = nil
}
