// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: assistant.proto

package api

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the AI integration whose model answers.
	IntegrationId string `protobuf:"bytes,1,opt,name=integration_id,json=integrationId,proto3" json:"integration_id,omitempty"`
	// The conversation so far, oldest first, ending with the user's new message.
	// No conversation state is kept on the server: the client sends the whole
	// history it wants the model to see.
	Conversation []*ChatMessage `protobuf:"bytes,2,rep,name=conversation,proto3" json:"conversation,omitempty"`
	// Optional identifier of an event the question is about. The event itself is
	// never taken from the client: the assistant reads it through the tools, so
	// that what the model sees is what the system recorded.
	EventId *string `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3,oneof" json:"event_id,omitempty"`
	// What the assistant is being asked to do: "chat" (the default), "explain"
	// for one runtime event, "digest" for a summary of a period, or "support"
	// to help the user write a support request. The mode only selects the
	// instructions the assistant is given; it never widens what it may do.
	Mode *string `protobuf:"bytes,4,opt,name=mode,proto3,oneof" json:"mode,omitempty"`
	// Approval of a tool call the assistant asked about in the previous turn,
	// carrying the identifier from that Confirmation. It is the only way a tool
	// that changes anything is ever run.
	ConfirmId *string `protobuf:"bytes,5,opt,name=confirm_id,json=confirmId,proto3,oneof" json:"confirm_id,omitempty"`
	// Which half of the product event_id belongs to: "runtime" (the default) or
	// "admission". The two are read with different tools, and an identifier alone
	// does not say which, so a client that opens a chat from an event page has to
	// say. Empty means runtime, for clients written before admission existed.
	EventKind *string `protobuf:"bytes,6,opt,name=event_kind,json=eventKind,proto3,oneof" json:"event_kind,omitempty"`
	// Identifier of the stored conversation this turn belongs to. Empty starts a
	// new one, whose identifier comes back in the Done chunk.
	ChatId        *string `protobuf:"bytes,7,opt,name=chat_id,json=chatId,proto3,oneof" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatReq) Reset() {
	*x = ChatReq{}
	mi := &file_assistant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReq) ProtoMessage() {}

func (x *ChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReq.ProtoReflect.Descriptor instead.
func (*ChatReq) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{0}
}

func (x *ChatReq) GetIntegrationId() string {
	if x != nil {
		return x.IntegrationId
	}
	return ""
}

func (x *ChatReq) GetConversation() []*ChatMessage {
	if x != nil {
		return x.Conversation
	}
	return nil
}

func (x *ChatReq) GetEventId() string {
	if x != nil && x.EventId != nil {
		return *x.EventId
	}
	return ""
}

func (x *ChatReq) GetMode() string {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return ""
}

func (x *ChatReq) GetConfirmId() string {
	if x != nil && x.ConfirmId != nil {
		return *x.ConfirmId
	}
	return ""
}

func (x *ChatReq) GetEventKind() string {
	if x != nil && x.EventKind != nil {
		return *x.EventKind
	}
	return ""
}

func (x *ChatReq) GetChatId() string {
	if x != nil && x.ChatId != nil {
		return *x.ChatId
	}
	return ""
}

type ChatMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Role of the author: "user" or "assistant". Any other value is rejected;
	// tool traffic belongs to the server side of the loop and is not replayed
	// by clients.
	Role          string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_assistant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ChatChunk is one piece of the answer. Exactly one field is set.
type ChatChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Chunk:
	//
	//	*ChatChunk_Delta
	//	*ChatChunk_ToolActivity
	//	*ChatChunk_Done
	//	*ChatChunk_Confirmation
	//	*ChatChunk_Secret
	//	*ChatChunk_Suggestions
	Chunk         isChatChunk_Chunk `protobuf_oneof:"chunk"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatChunk) Reset() {
	*x = ChatChunk{}
	mi := &file_assistant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatChunk) ProtoMessage() {}

func (x *ChatChunk) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatChunk.ProtoReflect.Descriptor instead.
func (*ChatChunk) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{2}
}

func (x *ChatChunk) GetChunk() isChatChunk_Chunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ChatChunk) GetDelta() string {
	if x != nil {
		if x, ok := x.Chunk.(*ChatChunk_Delta); ok {
			return x.Delta
		}
	}
	return ""
}

func (x *ChatChunk) GetToolActivity() *ToolActivity {
	if x != nil {
		if x, ok := x.Chunk.(*ChatChunk_ToolActivity); ok {
			return x.ToolActivity
		}
	}
	return nil
}

func (x *ChatChunk) GetDone() *Done {
	if x != nil {
		if x, ok := x.Chunk.(*ChatChunk_Done); ok {
			return x.Done
		}
	}
	return nil
}

func (x *ChatChunk) GetConfirmation() *Confirmation {
	if x != nil {
		if x, ok := x.Chunk.(*ChatChunk_Confirmation); ok {
			return x.Confirmation
		}
	}
	return nil
}

func (x *ChatChunk) GetSecret() *Secret {
	if x != nil {
		if x, ok := x.Chunk.(*ChatChunk_Secret); ok {
			return x.Secret
		}
	}
	return nil
}

func (x *ChatChunk) GetSuggestions() *Suggestions {
	if x != nil {
		if x, ok := x.Chunk.(*ChatChunk_Suggestions); ok {
			return x.Suggestions
		}
	}
	return nil
}

type isChatChunk_Chunk interface {
	isChatChunk_Chunk()
}

type ChatChunk_Delta struct {
	// delta is a piece of the answer's text, to be appended as it arrives.
	Delta string `protobuf:"bytes,1,opt,name=delta,proto3,oneof"`
}

type ChatChunk_ToolActivity struct {
	// tool_activity reports that the assistant started or finished a tool.
	ToolActivity *ToolActivity `protobuf:"bytes,2,opt,name=tool_activity,json=toolActivity,proto3,oneof"`
}

type ChatChunk_Done struct {
	// done ends the answer.
	Done *Done `protobuf:"bytes,3,opt,name=done,proto3,oneof"`
}

type ChatChunk_Confirmation struct {
	// confirmation asks the user to approve a tool that would change the
	// product. The answer stops there until they do.
	Confirmation *Confirmation `protobuf:"bytes,4,opt,name=confirmation,proto3,oneof"`
}

type ChatChunk_Secret struct {
	// secret carries a credential an approved tool produced. It is delivered
	// to the user and deliberately kept out of the conversation the model
	// sees, so that it never reaches an LLM provider.
	Secret *Secret `protobuf:"bytes,5,opt,name=secret,proto3,oneof"`
}

type ChatChunk_Suggestions struct {
	// suggestions are follow-up questions to offer under the answer.
	Suggestions *Suggestions `protobuf:"bytes,6,opt,name=suggestions,proto3,oneof"`
}

func (*ChatChunk_Delta) isChatChunk_Chunk() {}

func (*ChatChunk_ToolActivity) isChatChunk_Chunk() {}

func (*ChatChunk_Done) isChatChunk_Chunk() {}

func (*ChatChunk_Confirmation) isChatChunk_Chunk() {}

func (*ChatChunk_Secret) isChatChunk_Chunk() {}

func (*ChatChunk_Suggestions) isChatChunk_Chunk() {}

// Suggestions are follow-up questions to offer under the answer, written by the
// model from the exchange it just had. They arrive once, just before Done.
type Suggestions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []string               `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Suggestions) Reset() {
	*x = Suggestions{}
	mi := &file_assistant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Suggestions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Suggestions) ProtoMessage() {}

func (x *Suggestions) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Suggestions.ProtoReflect.Descriptor instead.
func (*Suggestions) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{3}
}

func (x *Suggestions) GetQuestions() []string {
	if x != nil {
		return x.Questions
	}
	return nil
}

type ToolActivity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the tool, for example search_docs.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Phase is "started" or "finished".
	Phase string `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	// error is set on a finished phase when the tool failed. The assistant
	// carries on: a failed tool is an answer the model has to account for.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolActivity) Reset() {
	*x = ToolActivity{}
	mi := &file_assistant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolActivity) ProtoMessage() {}

func (x *ToolActivity) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolActivity.ProtoReflect.Descriptor instead.
func (*ToolActivity) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{4}
}

func (x *ToolActivity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolActivity) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ToolActivity) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Confirmation is a tool call the assistant wants to make and may not make on
// its own: it would create, change or delete something in the product.
type Confirmation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier to send back as confirm_id to approve this exact call. It is
	// valid for a few minutes, once, and only for the user it was issued to.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the tool, for example create_rule.
	Tool string `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	// Human readable title of the tool, as the MCP server named it.
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// The arguments the tool would be called with, as pretty-printed JSON. They
	// come from the model, so the user is shown exactly what would be sent.
	Arguments string `protobuf:"bytes,4,opt,name=arguments,proto3" json:"arguments,omitempty"`
	// destructive is set when the call removes something rather than adds it.
	Destructive   bool `protobuf:"varint,5,opt,name=destructive,proto3" json:"destructive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Confirmation) Reset() {
	*x = Confirmation{}
	mi := &file_assistant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Confirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmation) ProtoMessage() {}

func (x *Confirmation) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmation.ProtoReflect.Descriptor instead.
func (*Confirmation) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{5}
}

func (x *Confirmation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Confirmation) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *Confirmation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Confirmation) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

func (x *Confirmation) GetDestructive() bool {
	if x != nil {
		return x.Destructive
	}
	return false
}

// Secret is a credential produced by an approved tool call. It is shown once:
// the product stores only a hash of it.
type Secret struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What the secret is, for example "API token ci-bot".
	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// The secret itself.
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// How the secret is to be handled.
	Note          string `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_assistant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{6}
}

func (x *Secret) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Secret) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Secret) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type Done struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stop_reason is "end_turn" when the assistant finished on its own,
	// "confirmation_required" when it is waiting for the user to approve a tool
	// call, "max_iterations" when the agent loop ran out of steps, or "error".
	StopReason string `protobuf:"bytes,1,opt,name=stop_reason,json=stopReason,proto3" json:"stop_reason,omitempty"`
	// error is set when stop_reason is "error".
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// iterations is how many model turns the answer took.
	Iterations uint32 `protobuf:"varint,3,opt,name=iterations,proto3" json:"iterations,omitempty"`
	// chat_id is the stored conversation this turn was written to, so that a
	// client which started a new one learns where to continue it.
	ChatId        string `protobuf:"bytes,4,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Done) Reset() {
	*x = Done{}
	mi := &file_assistant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Done) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Done) ProtoMessage() {}

func (x *Done) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Done.ProtoReflect.Descriptor instead.
func (*Done) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{7}
}

func (x *Done) GetStopReason() string {
	if x != nil {
		return x.StopReason
	}
	return ""
}

func (x *Done) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Done) GetIterations() uint32 {
	if x != nil {
		return x.Iterations
	}
	return 0
}

func (x *Done) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

// Chat is one stored conversation. In a listing its messages are left out.
type Chat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Title is the opening of the first question.
	Title     string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt string `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// The event the conversation was opened from, when it was opened from one.
	EventId   string `protobuf:"bytes,5,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventKind string `protobuf:"bytes,6,opt,name=event_kind,json=eventKind,proto3" json:"event_kind,omitempty"`
	Mode      string `protobuf:"bytes,7,opt,name=mode,proto3" json:"mode,omitempty"`
	// How many turns the conversation holds. Filled in listings, where the
	// messages themselves are not returned.
	MessageCount  uint32         `protobuf:"varint,8,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	Messages      []*ChatMessage `protobuf:"bytes,9,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_assistant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{8}
}

func (x *Chat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chat) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Chat) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Chat) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Chat) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Chat) GetEventKind() string {
	if x != nil {
		return x.EventKind
	}
	return ""
}

func (x *Chat) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Chat) GetMessageCount() uint32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *Chat) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ListChatsReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How many conversations to return, newest first. Zero means the default.
	Limit         uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatsReq) Reset() {
	*x = ListChatsReq{}
	mi := &file_assistant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatsReq) ProtoMessage() {}

func (x *ListChatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatsReq.ProtoReflect.Descriptor instead.
func (*ListChatsReq) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{9}
}

func (x *ListChatsReq) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListChatsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*Chat                `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatsResp) Reset() {
	*x = ListChatsResp{}
	mi := &file_assistant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatsResp) ProtoMessage() {}

func (x *ListChatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatsResp.ProtoReflect.Descriptor instead.
func (*ListChatsResp) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{10}
}

func (x *ListChatsResp) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

type ReadChatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChatReq) Reset() {
	*x = ReadChatReq{}
	mi := &file_assistant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChatReq) ProtoMessage() {}

func (x *ReadChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChatReq.ProtoReflect.Descriptor instead.
func (*ReadChatReq) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{11}
}

func (x *ReadChatReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadChatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *Chat                  `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChatResp) Reset() {
	*x = ReadChatResp{}
	mi := &file_assistant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChatResp) ProtoMessage() {}

func (x *ReadChatResp) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChatResp.ProtoReflect.Descriptor instead.
func (*ReadChatResp) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{12}
}

func (x *ReadChatResp) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type DeleteChatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatReq) Reset() {
	*x = DeleteChatReq{}
	mi := &file_assistant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatReq) ProtoMessage() {}

func (x *DeleteChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatReq.ProtoReflect.Descriptor instead.
func (*DeleteChatReq) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteChatReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteChatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatResp) Reset() {
	*x = DeleteChatResp{}
	mi := &file_assistant_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatResp) ProtoMessage() {}

func (x *DeleteChatResp) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatResp.ProtoReflect.Descriptor instead.
func (*DeleteChatResp) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteChatResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_assistant_proto protoreflect.FileDescriptor

const file_assistant_proto_rawDesc = "" +
	"\n" +
	"\x0fassistant.proto\x12\tassistant\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xcb\x02\n" +
	"\aChatReq\x12%\n" +
	"\x0eintegration_id\x18\x01 \x01(\tR\rintegrationId\x12:\n" +
	"\fconversation\x18\x02 \x03(\v2\x16.assistant.ChatMessageR\fconversation\x12\x1e\n" +
	"\bevent_id\x18\x03 \x01(\tH\x00R\aeventId\x88\x01\x01\x12\x17\n" +
	"\x04mode\x18\x04 \x01(\tH\x01R\x04mode\x88\x01\x01\x12\"\n" +
	"\n" +
	"confirm_id\x18\x05 \x01(\tH\x02R\tconfirmId\x88\x01\x01\x12\"\n" +
	"\n" +
	"event_kind\x18\x06 \x01(\tH\x03R\teventKind\x88\x01\x01\x12\x1c\n" +
	"\achat_id\x18\a \x01(\tH\x04R\x06chatId\x88\x01\x01B\v\n" +
	"\t_event_idB\a\n" +
	"\x05_modeB\r\n" +
	"\v_confirm_idB\r\n" +
	"\v_event_kindB\n" +
	"\n" +
	"\b_chat_id\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xbb\x02\n" +
	"\tChatChunk\x12\x16\n" +
	"\x05delta\x18\x01 \x01(\tH\x00R\x05delta\x12>\n" +
	"\rtool_activity\x18\x02 \x01(\v2\x17.assistant.ToolActivityH\x00R\ftoolActivity\x12%\n" +
	"\x04done\x18\x03 \x01(\v2\x0f.assistant.DoneH\x00R\x04done\x12=\n" +
	"\fconfirmation\x18\x04 \x01(\v2\x17.assistant.ConfirmationH\x00R\fconfirmation\x12+\n" +
	"\x06secret\x18\x05 \x01(\v2\x11.assistant.SecretH\x00R\x06secret\x12:\n" +
	"\vsuggestions\x18\x06 \x01(\v2\x16.assistant.SuggestionsH\x00R\vsuggestionsB\a\n" +
	"\x05chunk\"+\n" +
	"\vSuggestions\x12\x1c\n" +
	"\tquestions\x18\x01 \x03(\tR\tquestions\"N\n" +
	"\fToolActivity\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x88\x01\n" +
	"\fConfirmation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1c\n" +
	"\targuments\x18\x04 \x01(\tR\targuments\x12 \n" +
	"\vdestructive\x18\x05 \x01(\bR\vdestructive\"H\n" +
	"\x06Secret\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\"v\n" +
	"\x04Done\x12\x1f\n" +
	"\vstop_reason\x18\x01 \x01(\tR\n" +
	"stopReason\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1e\n" +
	"\n" +
	"iterations\x18\x03 \x01(\rR\n" +
	"iterations\x12\x17\n" +
	"\achat_id\x18\x04 \x01(\tR\x06chatId\"\x91\x02\n" +
	"\x04Chat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\x12\x19\n" +
	"\bevent_id\x18\x05 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_kind\x18\x06 \x01(\tR\teventKind\x12\x12\n" +
	"\x04mode\x18\a \x01(\tR\x04mode\x12#\n" +
	"\rmessage_count\x18\b \x01(\rR\fmessageCount\x122\n" +
	"\bmessages\x18\t \x03(\v2\x16.assistant.ChatMessageR\bmessages\"$\n" +
	"\fListChatsReq\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\"6\n" +
	"\rListChatsResp\x12%\n" +
	"\x05chats\x18\x01 \x03(\v2\x0f.assistant.ChatR\x05chats\"\x1d\n" +
	"\vReadChatReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\fReadChatResp\x12#\n" +
	"\x04chat\x18\x01 \x01(\v2\x0f.assistant.ChatR\x04chat\"\x1f\n" +
	"\rDeleteChatReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\" \n" +
	"\x0eDeleteChatResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x97\x03\n" +
	"\x13AssistantController\x12U\n" +
	"\x04Chat\x12\x12.assistant.ChatReq\x1a\x14.assistant.ChatChunk\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/assistant/chat0\x01\x12_\n" +
	"\tListChats\x12\x17.assistant.ListChatsReq\x1a\x18.assistant.ListChatsResp\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/assistant/chats\x12`\n" +
	"\bReadChat\x12\x16.assistant.ReadChatReq\x1a\x17.assistant.ReadChatResp\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/assistant/chat/{id}\x12f\n" +
	"\n" +
	"DeleteChat\x12\x18.assistant.DeleteChatReq\x1a\x19.assistant.DeleteChatResp\"#\x82\xd3\xe4\x93\x02\x1d*\x1b/api/v1/assistant/chat/{id}B\x1b\x92A\x11\x12\x0f\n" +
	"\rAssistant APIZ\x05./apib\x06proto3"

var (
	file_assistant_proto_rawDescOnce sync.Once
	file_assistant_proto_rawDescData []byte
)

func file_assistant_proto_rawDescGZIP() []byte {
	file_assistant_proto_rawDescOnce.Do(func() {
		file_assistant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assistant_proto_rawDesc), len(file_assistant_proto_rawDesc)))
	})
	return file_assistant_proto_rawDescData
}

var file_assistant_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_assistant_proto_goTypes = []any{
	(*ChatReq)(nil),        // 0: assistant.ChatReq
	(*ChatMessage)(nil),    // 1: assistant.ChatMessage
	(*ChatChunk)(nil),      // 2: assistant.ChatChunk
	(*Suggestions)(nil),    // 3: assistant.Suggestions
	(*ToolActivity)(nil),   // 4: assistant.ToolActivity
	(*Confirmation)(nil),   // 5: assistant.Confirmation
	(*Secret)(nil),         // 6: assistant.Secret
	(*Done)(nil),           // 7: assistant.Done
	(*Chat)(nil),           // 8: assistant.Chat
	(*ListChatsReq)(nil),   // 9: assistant.ListChatsReq
	(*ListChatsResp)(nil),  // 10: assistant.ListChatsResp
	(*ReadChatReq)(nil),    // 11: assistant.ReadChatReq
	(*ReadChatResp)(nil),   // 12: assistant.ReadChatResp
	(*DeleteChatReq)(nil),  // 13: assistant.DeleteChatReq
	(*DeleteChatResp)(nil), // 14: assistant.DeleteChatResp
}
var file_assistant_proto_depIdxs = []int32{
	1,  // 0: assistant.ChatReq.conversation:type_name -> assistant.ChatMessage
	4,  // 1: assistant.ChatChunk.tool_activity:type_name -> assistant.ToolActivity
	7,  // 2: assistant.ChatChunk.done:type_name -> assistant.Done
	5,  // 3: assistant.ChatChunk.confirmation:type_name -> assistant.Confirmation
	6,  // 4: assistant.ChatChunk.secret:type_name -> assistant.Secret
	3,  // 5: assistant.ChatChunk.suggestions:type_name -> assistant.Suggestions
	1,  // 6: assistant.Chat.messages:type_name -> assistant.ChatMessage
	8,  // 7: assistant.ListChatsResp.chats:type_name -> assistant.Chat
	8,  // 8: assistant.ReadChatResp.chat:type_name -> assistant.Chat
	0,  // 9: assistant.AssistantController.Chat:input_type -> assistant.ChatReq
	9,  // 10: assistant.AssistantController.ListChats:input_type -> assistant.ListChatsReq
	11, // 11: assistant.AssistantController.ReadChat:input_type -> assistant.ReadChatReq
	13, // 12: assistant.AssistantController.DeleteChat:input_type -> assistant.DeleteChatReq
	2,  // 13: assistant.AssistantController.Chat:output_type -> assistant.ChatChunk
	10, // 14: assistant.AssistantController.ListChats:output_type -> assistant.ListChatsResp
	12, // 15: assistant.AssistantController.ReadChat:output_type -> assistant.ReadChatResp
	14, // 16: assistant.AssistantController.DeleteChat:output_type -> assistant.DeleteChatResp
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_assistant_proto_init() }
func file_assistant_proto_init() {
	if File_assistant_proto != nil {
		return
	}
	file_assistant_proto_msgTypes[0].OneofWrappers = []any{}
	file_assistant_proto_msgTypes[2].OneofWrappers = []any{
		(*ChatChunk_Delta)(nil),
		(*ChatChunk_ToolActivity)(nil),
		(*ChatChunk_Done)(nil),
		(*ChatChunk_Confirmation)(nil),
		(*ChatChunk_Secret)(nil),
		(*ChatChunk_Suggestions)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assistant_proto_rawDesc), len(file_assistant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assistant_proto_goTypes,
		DependencyIndexes: file_assistant_proto_depIdxs,
		MessageInfos:      file_assistant_proto_msgTypes,
	}.Build()
	File_assistant_proto = out.File
	file_assistant_proto_goTypes = nil
	file_assistant_proto_depIdxs = nil
}
