// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: notifier.proto

package api

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing notification's id and event to notify about.
type Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*Message_RuntimeEvent
	Event         isMessage_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_notifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_notifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_notifier_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *Message) GetEvent() isMessage_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Message) GetRuntimeEvent() *RuntimeEvent {
	if x != nil {
		if x, ok := x.Event.(*Message_RuntimeEvent); ok {
			return x.RuntimeEvent
		}
	}
	return nil
}

type isMessage_Event interface {
	isMessage_Event()
}

type Message_RuntimeEvent struct {
	RuntimeEvent *RuntimeEvent `protobuf:"bytes,5,opt,name=runtime_event,json=runtimeEvent,proto3,oneof"`
}

func (*Message_RuntimeEvent) isMessage_Event() {}

type NotifyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Message             `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyReq) Reset() {
	*x = NotifyReq{}
	mi := &file_notifier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyReq) ProtoMessage() {}

func (x *NotifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_notifier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyReq.ProtoReflect.Descriptor instead.
func (*NotifyReq) Descriptor() ([]byte, []int) {
	return file_notifier_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyReq) GetNotifications() []*Message {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type RuntimeEvent struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Event        *RuntimeEvent_Event    `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Severity     string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	RegisteredAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	RuleName     string                 `protobuf:"bytes,4,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	Block        bool                   `protobuf:"varint,5,opt,name=block,proto3" json:"block,omitempty"`
	// id of event in history-api
	EventId       string `protobuf:"bytes,6,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeEvent) Reset() {
	*x = RuntimeEvent{}
	mi := &file_notifier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeEvent) ProtoMessage() {}

func (x *RuntimeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_notifier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeEvent.ProtoReflect.Descriptor instead.
func (*RuntimeEvent) Descriptor() ([]byte, []int) {
	return file_notifier_proto_rawDescGZIP(), []int{2}
}

func (x *RuntimeEvent) GetEvent() *RuntimeEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *RuntimeEvent) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *RuntimeEvent) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *RuntimeEvent) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *RuntimeEvent) GetBlock() bool {
	if x != nil {
		return x.Block
	}
	return false
}

func (x *RuntimeEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type RuntimeEvent_Event struct {
	state               protoimpl.MessageState       `protogen:"open.v1"`
	Threats             []*RuntimeEvent_Event_Threat `protobuf:"bytes,1,rep,name=threats,proto3" json:"threats,omitempty"`
	EventType           string                       `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ProcessPid          *uint32                      `protobuf:"varint,3,opt,name=process_pid,json=processPid,proto3,oneof" json:"process_pid,omitempty"`
	ProcessUid          *uint32                      `protobuf:"varint,4,opt,name=process_uid,json=processUid,proto3,oneof" json:"process_uid,omitempty"`
	ProcessBinary       string                       `protobuf:"bytes,5,opt,name=process_binary,json=processBinary,proto3" json:"process_binary,omitempty"`
	ProcessArguments    string                       `protobuf:"bytes,6,opt,name=process_arguments,json=processArguments,proto3" json:"process_arguments,omitempty"`
	ProcessSetuid       *uint32                      `protobuf:"varint,7,opt,name=process_setuid,json=processSetuid,proto3,oneof" json:"process_setuid,omitempty"`
	ProcessSetgid       *uint32                      `protobuf:"varint,8,opt,name=process_setgid,json=processSetgid,proto3,oneof" json:"process_setgid,omitempty"`
	ProcessCapEffective []string                     `protobuf:"bytes,9,rep,name=process_cap_effective,json=processCapEffective,proto3" json:"process_cap_effective,omitempty"`
	ProcessCapPermitted []string                     `protobuf:"bytes,10,rep,name=process_cap_permitted,json=processCapPermitted,proto3" json:"process_cap_permitted,omitempty"`
	ParentPid           *uint32                      `protobuf:"varint,11,opt,name=parent_pid,json=parentPid,proto3,oneof" json:"parent_pid,omitempty"`
	ParentUid           *uint32                      `protobuf:"varint,12,opt,name=parent_uid,json=parentUid,proto3,oneof" json:"parent_uid,omitempty"`
	ParentBinary        string                       `protobuf:"bytes,13,opt,name=parent_binary,json=parentBinary,proto3" json:"parent_binary,omitempty"`
	ParentArguments     string                       `protobuf:"bytes,14,opt,name=parent_arguments,json=parentArguments,proto3" json:"parent_arguments,omitempty"`
	PodNamespace        string                       `protobuf:"bytes,15,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	PodName             string                       `protobuf:"bytes,16,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	ContainerId         string                       `protobuf:"bytes,17,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ContainerName       string                       `protobuf:"bytes,18,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	ContainerImage      string                       `protobuf:"bytes,19,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"`
	NodeName            string                       `protobuf:"bytes,20,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	FunctionName        string                       `protobuf:"bytes,21,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	// function_args represents json-serialized list of function's args
	FunctionArgs string `protobuf:"bytes,22,opt,name=function_args,json=functionArgs,proto3" json:"function_args,omitempty"`
	// function_return represents json-serialized function's return value
	FunctionReturn string `protobuf:"bytes,23,opt,name=function_return,json=functionReturn,proto3" json:"function_return,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RuntimeEvent_Event) Reset() {
	*x = RuntimeEvent_Event{}
	mi := &file_notifier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeEvent_Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeEvent_Event) ProtoMessage() {}

func (x *RuntimeEvent_Event) ProtoReflect() protoreflect.Message {
	mi := &file_notifier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeEvent_Event.ProtoReflect.Descriptor instead.
func (*RuntimeEvent_Event) Descriptor() ([]byte, []int) {
	return file_notifier_proto_rawDescGZIP(), []int{2, 0}
}

func (x *RuntimeEvent_Event) GetThreats() []*RuntimeEvent_Event_Threat {
	if x != nil {
		return x.Threats
	}
	return nil
}

func (x *RuntimeEvent_Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *RuntimeEvent_Event) GetProcessPid() uint32 {
	if x != nil && x.ProcessPid != nil {
		return *x.ProcessPid
	}
	return 0
}

func (x *RuntimeEvent_Event) GetProcessUid() uint32 {
	if x != nil && x.ProcessUid != nil {
		return *x.ProcessUid
	}
	return 0
}

func (x *RuntimeEvent_Event) GetProcessBinary() string {
	if x != nil {
		return x.ProcessBinary
	}
	return ""
}

func (x *RuntimeEvent_Event) GetProcessArguments() string {
	if x != nil {
		return x.ProcessArguments
	}
	return ""
}

func (x *RuntimeEvent_Event) GetProcessSetuid() uint32 {
	if x != nil && x.ProcessSetuid != nil {
		return *x.ProcessSetuid
	}
	return 0
}

func (x *RuntimeEvent_Event) GetProcessSetgid() uint32 {
	if x != nil && x.ProcessSetgid != nil {
		return *x.ProcessSetgid
	}
	return 0
}

func (x *RuntimeEvent_Event) GetProcessCapEffective() []string {
	if x != nil {
		return x.ProcessCapEffective
	}
	return nil
}

func (x *RuntimeEvent_Event) GetProcessCapPermitted() []string {
	if x != nil {
		return x.ProcessCapPermitted
	}
	return nil
}

func (x *RuntimeEvent_Event) GetParentPid() uint32 {
	if x != nil && x.ParentPid != nil {
		return *x.ParentPid
	}
	return 0
}

func (x *RuntimeEvent_Event) GetParentUid() uint32 {
	if x != nil && x.ParentUid != nil {
		return *x.ParentUid
	}
	return 0
}

func (x *RuntimeEvent_Event) GetParentBinary() string {
	if x != nil {
		return x.ParentBinary
	}
	return ""
}

func (x *RuntimeEvent_Event) GetParentArguments() string {
	if x != nil {
		return x.ParentArguments
	}
	return ""
}

func (x *RuntimeEvent_Event) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *RuntimeEvent_Event) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *RuntimeEvent_Event) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *RuntimeEvent_Event) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *RuntimeEvent_Event) GetContainerImage() string {
	if x != nil {
		return x.ContainerImage
	}
	return ""
}

func (x *RuntimeEvent_Event) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *RuntimeEvent_Event) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *RuntimeEvent_Event) GetFunctionArgs() string {
	if x != nil {
		return x.FunctionArgs
	}
	return ""
}

func (x *RuntimeEvent_Event) GetFunctionReturn() string {
	if x != nil {
		return x.FunctionReturn
	}
	return ""
}

type RuntimeEvent_Event_Threat struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DetectorId          string                 `protobuf:"bytes,1,opt,name=detector_id,json=detectorId,proto3" json:"detector_id,omitempty"`
	DetectorName        string                 `protobuf:"bytes,2,opt,name=detector_name,json=detectorName,proto3" json:"detector_name,omitempty"`
	DetectorVersion     uint32                 `protobuf:"varint,3,opt,name=detector_version,json=detectorVersion,proto3" json:"detector_version,omitempty"`
	DetectorDescription string                 `protobuf:"bytes,4,opt,name=detector_description,json=detectorDescription,proto3" json:"detector_description,omitempty"`
	Severity            string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RuntimeEvent_Event_Threat) Reset() {
	*x = RuntimeEvent_Event_Threat{}
	mi := &file_notifier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeEvent_Event_Threat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeEvent_Event_Threat) ProtoMessage() {}

func (x *RuntimeEvent_Event_Threat) ProtoReflect() protoreflect.Message {
	mi := &file_notifier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeEvent_Event_Threat.ProtoReflect.Descriptor instead.
func (*RuntimeEvent_Event_Threat) Descriptor() ([]byte, []int) {
	return file_notifier_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *RuntimeEvent_Event_Threat) GetDetectorId() string {
	if x != nil {
		return x.DetectorId
	}
	return ""
}

func (x *RuntimeEvent_Event_Threat) GetDetectorName() string {
	if x != nil {
		return x.DetectorName
	}
	return ""
}

func (x *RuntimeEvent_Event_Threat) GetDetectorVersion() uint32 {
	if x != nil {
		return x.DetectorVersion
	}
	return 0
}

func (x *RuntimeEvent_Event_Threat) GetDetectorDescription() string {
	if x != nil {
		return x.DetectorDescription
	}
	return ""
}

func (x *RuntimeEvent_Event_Threat) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

var File_notifier_proto protoreflect.FileDescriptor

const file_notifier_proto_rawDesc = "" +
	"\n" +
	"\x0enotifier.proto\x12\bnotifier\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"z\n" +
	"\aMessage\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12=\n" +
	"\rruntime_event\x18\x05 \x01(\v2\x16.notifier.RuntimeEventH\x00R\fruntimeEventB\a\n" +
	"\x05event\"D\n" +
	"\tNotifyReq\x127\n" +
	"\rnotifications\x18\x01 \x03(\v2\x11.notifier.MessageR\rnotifications\"\xbf\v\n" +
	"\fRuntimeEvent\x122\n" +
	"\x05event\x18\x01 \x01(\v2\x1c.notifier.RuntimeEvent.EventR\x05event\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12?\n" +
	"\rregistered_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x12\x1b\n" +
	"\trule_name\x18\x04 \x01(\tR\bruleName\x12\x14\n" +
	"\x05block\x18\x05 \x01(\bR\x05block\x12\x19\n" +
	"\bevent_id\x18\x06 \x01(\tR\aeventId\x1a\xcf\t\n" +
	"\x05Event\x12=\n" +
	"\athreats\x18\x01 \x03(\v2#.notifier.RuntimeEvent.Event.ThreatR\athreats\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12$\n" +
	"\vprocess_pid\x18\x03 \x01(\rH\x00R\n" +
	"processPid\x88\x01\x01\x12$\n" +
	"\vprocess_uid\x18\x04 \x01(\rH\x01R\n" +
	"processUid\x88\x01\x01\x12%\n" +
	"\x0eprocess_binary\x18\x05 \x01(\tR\rprocessBinary\x12+\n" +
	"\x11process_arguments\x18\x06 \x01(\tR\x10processArguments\x12*\n" +
	"\x0eprocess_setuid\x18\a \x01(\rH\x02R\rprocessSetuid\x88\x01\x01\x12*\n" +
	"\x0eprocess_setgid\x18\b \x01(\rH\x03R\rprocessSetgid\x88\x01\x01\x122\n" +
	"\x15process_cap_effective\x18\t \x03(\tR\x13processCapEffective\x122\n" +
	"\x15process_cap_permitted\x18\n" +
	" \x03(\tR\x13processCapPermitted\x12\"\n" +
	"\n" +
	"parent_pid\x18\v \x01(\rH\x04R\tparentPid\x88\x01\x01\x12\"\n" +
	"\n" +
	"parent_uid\x18\f \x01(\rH\x05R\tparentUid\x88\x01\x01\x12#\n" +
	"\rparent_binary\x18\r \x01(\tR\fparentBinary\x12)\n" +
	"\x10parent_arguments\x18\x0e \x01(\tR\x0fparentArguments\x12#\n" +
	"\rpod_namespace\x18\x0f \x01(\tR\fpodNamespace\x12\x19\n" +
	"\bpod_name\x18\x10 \x01(\tR\apodName\x12!\n" +
	"\fcontainer_id\x18\x11 \x01(\tR\vcontainerId\x12%\n" +
	"\x0econtainer_name\x18\x12 \x01(\tR\rcontainerName\x12'\n" +
	"\x0fcontainer_image\x18\x13 \x01(\tR\x0econtainerImage\x12\x1b\n" +
	"\tnode_name\x18\x14 \x01(\tR\bnodeName\x12#\n" +
	"\rfunction_name\x18\x15 \x01(\tR\ffunctionName\x12#\n" +
	"\rfunction_args\x18\x16 \x01(\tR\ffunctionArgs\x12'\n" +
	"\x0ffunction_return\x18\x17 \x01(\tR\x0efunctionReturn\x1a\xc8\x01\n" +
	"\x06Threat\x12\x1f\n" +
	"\vdetector_id\x18\x01 \x01(\tR\n" +
	"detectorId\x12#\n" +
	"\rdetector_name\x18\x02 \x01(\tR\fdetectorName\x12)\n" +
	"\x10detector_version\x18\x03 \x01(\rR\x0fdetectorVersion\x121\n" +
	"\x14detector_description\x18\x04 \x01(\tR\x13detectorDescription\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverityB\x0e\n" +
	"\f_process_pidB\x0e\n" +
	"\f_process_uidB\x11\n" +
	"\x0f_process_setuidB\x11\n" +
	"\x0f_process_setgidB\r\n" +
	"\v_parent_pidB\r\n" +
	"\v_parent_uid2\\\n" +
	"\bNotifier\x12P\n" +
	"\x06Notify\x12\x13.notifier.NotifyReq\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/notifyB\x1a\x92A\x10\x12\x0e\n" +
	"\fNotifier APIZ\x05./apib\x06proto3"

var (
	file_notifier_proto_rawDescOnce sync.Once
	file_notifier_proto_rawDescData []byte
)

func file_notifier_proto_rawDescGZIP() []byte {
	file_notifier_proto_rawDescOnce.Do(func() {
		file_notifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notifier_proto_rawDesc), len(file_notifier_proto_rawDesc)))
	})
	return file_notifier_proto_rawDescData
}

var file_notifier_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_notifier_proto_goTypes = []any{
	(*Message)(nil),                   // 0: notifier.Message
	(*NotifyReq)(nil),                 // 1: notifier.NotifyReq
	(*RuntimeEvent)(nil),              // 2: notifier.RuntimeEvent
	(*RuntimeEvent_Event)(nil),        // 3: notifier.RuntimeEvent.Event
	(*RuntimeEvent_Event_Threat)(nil), // 4: notifier.RuntimeEvent.Event.Threat
	(*timestamppb.Timestamp)(nil),     // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 6: google.protobuf.Empty
}
var file_notifier_proto_depIdxs = []int32{
	2, // 0: notifier.Message.runtime_event:type_name -> notifier.RuntimeEvent
	0, // 1: notifier.NotifyReq.notifications:type_name -> notifier.Message
	3, // 2: notifier.RuntimeEvent.event:type_name -> notifier.RuntimeEvent.Event
	5, // 3: notifier.RuntimeEvent.registered_at:type_name -> google.protobuf.Timestamp
	4, // 4: notifier.RuntimeEvent.Event.threats:type_name -> notifier.RuntimeEvent.Event.Threat
	1, // 5: notifier.Notifier.Notify:input_type -> notifier.NotifyReq
	6, // 6: notifier.Notifier.Notify:output_type -> google.protobuf.Empty
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_notifier_proto_init() }
func file_notifier_proto_init() {
	if File_notifier_proto != nil {
		return
	}
	file_notifier_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_RuntimeEvent)(nil),
	}
	file_notifier_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notifier_proto_rawDesc), len(file_notifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notifier_proto_goTypes,
		DependencyIndexes: file_notifier_proto_depIdxs,
		MessageInfos:      file_notifier_proto_msgTypes,
	}.Build()
	File_notifier_proto = out.File
	file_notifier_proto_goTypes = nil
	file_notifier_proto_depIdxs = nil
}
